# Perfil por defecto (desarrollo local)
spring.profiles.active=dev

# Puerto (Railway inyecta PORT)
server.port=${PORT:8080}

# JWT (igual para todos los entornos)
jwt.secret=miClaveSecretaSuperSegura123456
jwt.expiration=86400000