# ==========================================
# PERFIL SUPABASE - PRODUCCIÓN
# ==========================================

# PostgreSQL (Supabase)
spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Puerto
server.port=${PORT:8080}