# Nombre de la aplicación
spring.application.name=backend

# Puerto del servidor
server.port=8080

# =========================
# BASE DE DATOS H2 (MEMORIA)
# =========================
spring.datasource.url=jdbc:h2:mem:tiendadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# CONSOLA H2
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JWT CONFIG
# =========================
jwt.secret=miClaveSecretaSuperSeguraQueDebeSerLargaParaJWT2024
jwt.expiration=86400000

# =========================
# SUBIDA DE ARCHIVOS
# =========================
file.upload-dir=uploads