# ==========================================
# PERFIL POR DEFECTO (DESARROLLO LOCAL)
# ==========================================
spring.profiles.active=dev

# Puerto
server.port=${PORT:8080}

# JWT
jwt.secret=miClaveSecretaSuperSeguraParaJWT2024Con32Caracteres!
jwt.expiration=86400000